#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            clientId: 2cbd1dff018f5421c92f
#            clientSecret:  b26a903c3bf5cbb0373806756157096db04bc13e
#          idsvr:
#            client-name: Login with the Curity Identity Server
#            client-id: www
#            client-secret: 12345678
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope: openid, profile
#        provider:
#          idsvr:
#          issuer-uri: https://localhost:8443/oauth/v2/oauth-anonymous
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 2cbd1dff018f5421c92f
            clientSecret:  b26a903c3bf5cbb0373806756157096db04bc13e
          google:
            client-id: 438299388802-ksd66vi7r8kp7pepbfeqqvuh4ve37cp3.apps.googleusercontent.com
            client-secret: Xm0-AUxyGcttMYeh9DLhkT1p